### ISSUE TITLE
Support dynamic dark theme

### ISSUE THREAD

**Issue by MarcSkovMadsen** [Lightning-AI/pytorch-lightning#13507]
## 🚀 Feature

Support dark mode!

### Motivation

A lot of users prefer or require dark mode. The current lightning.ai logo (lower left corner) does not read well on a dark background (see lower, left corner of image below).

![image](https://user-images.githubusercontent.com/42288570/176993981-fba5b9c7-f0e6-412f-8b97-63e4bb11cd00.png)

## Additional Context

Users of the Panel framework that I am using can toggle the theme dynamically. I would like the lightning.ai app theme to be able to update accordingly.

cc @borda

**Comment by alecmerdler** [comment]
Thanks for the issue @MarcSkovMadsen! I appreciate you noticing this, it would bother me too. Since the UI being rendered in your app could be anything, it's difficult for us to guess what the theme is and which logo to render. I'll ask the design team what we can do in this case and check back once I have an answer.
