### ISSUE TITLE
CSVLogger column ordering is random

### ISSUE THREAD

**Issue by taromakino** [Lightning-AI/pytorch-lightning#18978]
### Bug description

I used to see a consistent column ordering in the output of my CSVLogger. If I call `self.log('a', ...)`, `self.log('b', ...)`, `self.log('c', ...)`, the column ordering would be `['a', 'b', 'c', 'step', 'epoch']`. However, now my column ordering is random across different runs, including the `step` and `epoch` columns.

### What version are you seeing the problem on?

v2.1

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @borda

**Comment by carmocca** [comment]
The columns could be sorted. This is the relevant piece of code: https://github.com/Lightning-AI/lightning/blob/master/src/lightning/fabric/loggers/csv_logs.py if you want to contribute.

Since ordering was basically undefined before behaviour that happened to be sorted, I will consider it a feature request instead of a bug

**Comment by b-harish** [comment]
Hi @carmocca, I am new to the Lightning ecosystem and I would love to learn and contribute. Would you like to assign this issue to me?

**Comment by b-harish** [comment]
Hi @carmocca 
I forked the repo and clone to my local system. Trying to play around the files and found a test_csv.py file under `tests/tests_pytorch/loggers/test_csv.py`. When I ran it throws `NoModuleFoundError: No module named 'lightning'`.
The lightning module available under `src` directory is not referring automatically. I am missing something.
I also gone through this page https://github.com/Lightning-AI/lightning/blob/master/tests/README.md

![image](https://github.com/Lightning-AI/lightning/assets/43300971/e520f0d9-8431-4d24-a045-73db04b37c9b)

Could you please help share some right resources to setup the dev environment and also understand the folder structure for beginners like me?

**Comment by b-harish** [comment]
@taromakino 
Could you please share the code you used while encountering the issue?

**Comment by carmocca** [comment]
@b-harish Were you able to install it? I think you missed this step
```bash
python -m pip install ".[dev, examples]"
```

**Comment by b-harish** [comment]
Thanks @carmocca I could run the files now. I tried the command and `pip install .` worked for me. 

I have a question with respect to the bug description and your comment on it.

It seems that the user wants the order of columns in the same way he calls the log function. Eg: if user calls `self.log(a..)`, `self.log(c..)` and `self.log(b..)`, the column ordering would be `[a, c, b]`

But in this [comment](https://github.com/Lightning-AI/lightning/issues/18978#issuecomment-1821221026), I could see you suggesting a sort on the columns. Did you mean actual sort? because then it would lead to `[a, b, c]` in the column order rather `[a, c, b]`.

Would you mind in clarifying the feature request?

**Comment by SarthakNikhal** [comment]
Any progress with this issue? Can I help with it?

**Comment by harishb00** [comment]
Hi @SarthakNikhal Thanks for extending your help. I have just raised a PR.
