### ISSUE TITLE
Add documentation for running multi-node training without slurm

### ISSUE THREAD

**Issue by ad12** [Lightning-AI/pytorch-lightning#19273]
### 📚 Documentation

I could not find a good reference for running multi-node training without slurm in the official docs. any documentation / help here would be much appreciated

cc @borda

**Comment by awaelchli** [comment]
@ad12 Here are all the ways you can do multi-node training with Trainer: https://lightning.ai/docs/pytorch/stable/levels/intermediate_level_14.html

**Comment by awaelchli** [comment]
Hey @ad12 could you take a look? Is the barebones approach described in the link I shared above what you are looking for?

**Comment by ad12** [comment]
Hey @awaelchli thanks for the link! these look good. i will test them and get back to you if we run into any issues

**Comment by ad12** [comment]
@awaelchli is there documentation on how to use Infiniband instead of Ethernet? Our cluster is infiniband connected but we are not sure whether the traffic is being sent over that or ethernet

**Comment by awaelchli** [comment]
We can't really document how to set up infiniband since this is more an infrastructure problem and we assume the cluster is already set up correctly. We know this is hard, that's why we created the [Lightning AI platform](https://lightning.ai). 

To check whether your traffic is going over infiniband, you can set the environment variable `NCCL_DEBUG=INFO`. This will print some info to your logs. This will tell you which network interface is used.

**Comment by awaelchli** [comment]
@ad12 Were you successful with running torchrun on your cluster?

**Comment by awaelchli** [comment]
I hope you made progress figuring this out on your infra. Happy to discuss further if anything pops up that needs improvement on the Lightning side.
