### ISSUE TITLE
LitProgressBar ignores TQDM_MINITERS

### ISSUE THREAD

**Issue by wouterzwerink** [Lightning-AI/pytorch-lightning#19346]
### Bug description

tqdm supports setting the environment variable `TQDM_MINITERS` to reduce the frequency of progress bar updates.
Since lightning trainer defaults to a TQDM progress bar, I expected this to work for lightning. However, pytorch lightnings trainer seems to ignore this.

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
export TQDM_MINITERS=5
python your_script.py


where script can be anything using a `pytorch_lightning.Trainer` with `progress_bar_enabled=True`
```

### Error messages and logs

-

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): Trainer
#- PyTorch Lightning Version (e.g., 1.5.0): 2.1.3
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0): 2.0.1
#- Python version (e.g., 3.9): 3.9
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source): poetry
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @awaelchli

**Comment by awaelchli** [comment]
@wouterzwerink Could you point us to the documentation for this? There is nothing like that in the source code of tqdm: https://github.com/search?q=repo:tqdm/tqdm+TQDM_MINITERS&type=code

**Comment by wouterzwerink** [comment]
@awaelchli yes unfortunately it's documented quite poorly!
They use this wrapper to overwrite their function defaults with environment variables
https://github.com/tqdm/tqdm/blob/4c956c20b83be4312460fc0c4812eeb3fef5e7df/tqdm/utils.py#L34

Applied here to TQDM:
https://github.com/tqdm/tqdm/blob/4c956c20b83be4312460fc0c4812eeb3fef5e7df/tqdm/std.py#L953

**Comment by awaelchli** [comment]
Thanks for the pointer! My blind guess is that maybe it doesn't work because we have our won small wrapper: https://github.com/Lightning-AI/pytorch-lightning/blob/ee9f17eb3ceb98c256d62128e07e61d4a97a9911/src/lightning/pytorch/callbacks/progress/tqdm_progress.py#L39
(but it should, since we call `super().__init__`?). Might be worth investigating what's going on there. Apart from that, I don't see why it wouldn't work because we're using tqdm quite plainly.

**Comment by wouterzwerink** [comment]
I tried just adding 
```python
if __name__ == "__main__":
    import time

    for _ in Tqdm(range(100)):
        time.sleep(1)
```
to the bottom of this file: [pytorch-lightning/src/lightning/pytorch/callbacks/progress/tqdm_progress.py](https://github.com/Lightning-AI/pytorch-lightning/blob/ee9f17eb3ceb98c256d62128e07e61d4a97a9911/src/lightning/pytorch/callbacks/progress/tqdm_progress.py#L39)

Calling it with and without TQDM_MINITERS set works as expected. So this Tqdm wrapper class is not causing any issues

**Comment by awaelchli** [comment]
Ah ok, I understand what miniters does now. miniters=x is supposed to update only ever x ticks. But then it makes sense that it doesn't work with Lightning because our progress bar implementation directly updates the bar (there is no iterable over it), because we need explicit and dynamic control over when the update happens: https://github.com/Lightning-AI/pytorch-lightning/blob/1a59097ab254e1cd85dc2cb88edfb6bc55087adc/src/lightning/pytorch/callbacks/progress/tqdm_progress.py#L448-L451

But I think there is probably an easy way to incorporate it by just grabbing the default refresh rate from the env variable here:
https://github.com/Lightning-AI/pytorch-lightning/blob/1a59097ab254e1cd85dc2cb88edfb6bc55087adc/src/lightning/pytorch/callbacks/progress/tqdm_progress.py#L429-L434

Would you be interested to contribute this change?
