### ISSUE TITLE
DeepSpeedStrategy integration

### ISSUE THREAD

**Issue by michele-milesi** [Lightning-AI/pytorch-lightning#19535]
### Description & Motivation

Hi, I would like to ask when the fabric DeepSpeed Strategy will be released in a stable version.
We are trying to finetune LLama2-70B-hf distributed with QLoRA.

### Additional context

@morettif and I tried to use the DeepSpeed Strategy for distributed training of a LLM (LLama2-70B-hf) and faced the following issues:

- For the precision management it was not possible to define it in both Fabric and DeepSpeed configs. Below the configs used are reported.
```json
{
  "zero_optimization": {
    "stage": 2,
    "contiguous_gradients": true,
    "overlap_comm": true,
    "zero_quantized_weights": true,
    "zero_quantized_gradients": true
  },
  "zero_allow_untested_optimizer": true,
  "gradient_accumulation_steps": 8,
  "train_batch_size": 32,
  "train_micro_batch_size_per_gpu": 2,
  "wall_clock_breakdown": false,
  "bf16": {
    "enabled": "auto"
  },
  "fp16": {
    "enabled": "false",
    "auto_cast": false,
    "loss_scale": 0,
    "initial_scale_power": 32,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "zero_hpz_partition_size": 16
}
```
- After resolving the precision problem, we setup the model and the optimizer (`bnb.optim.PagedAdamW` from bitsandbytes) with the `fabric.setup()` function. The optimizer returned by the setup function is not compatible with the torch schedulers (see below).
```python
scheduler1 = torch.optim.lr_scheduler.LambdaLR(
    optimizer, lambda step: step / warmup_steps
)
scheduler2 = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer, T_max=(max_steps - warmup_steps)
)
return torch.optim.lr_scheduler.SequentialLR(
    optimizer, [scheduler1, scheduler2], milestones=[warmup_steps]
)
``` 

Fabric was instantiated with the following configs:
- `devices = 4`
- `plugins = BitsandbytesPrecision("nf4-dq", "bf16-true")`
- `precision = None` 

cc @borda @awaelchli @carmocca

**Comment by awaelchli** [comment]
Hey @michele-milesi 

The DeepSpeed integration in Lightning exists since 2 years and has been maintained for a while. However since a few months now we haven't had the bandwidth to keep up with it. Our CI testing has the version of DeepSpeed at 0.9.3. The problem is the DeepSpeed project itself doesn't see good maintenance, and they are not writing tests for most of their commits. This poses challenges also for us as it is just a large effort to keep up resolving the issues. So the future is very uncertain. 

For sharded training (ZeRO) our FSDP support is the best for this at the moment, and is actively maintained.

The main limitation for you will be that precision plugins like BNB won't compose with the precision settings of the FSDP and DeepSpeed strategy. So in other words, you can't use BNB +  FSDP or DeepSpeed. We are aware of this and tracking the effort here: #18679. But it's not easy.

Sorry that I don't have better news.

**Comment by michele-milesi** [comment]
Thanks for your feedback
