### ISSUE TITLE
Notify LightningDataModule on exception

### ISSUE THREAD

**Issue by clumsy** [Lightning-AI/pytorch-lightning#19594]
### Description & Motivation

Callbacks have both `teardown` and `on_exception` to gracefully terminate, but `LightningDataModule` does not have `on_exception` and `teardown` is only seem to be called when fit/validate/predict/test finished successfully.

### Pitch

Can exception cases be also added to `LightningDataModule` contract? Or maybe add `on_exception`. 

### Alternatives

Otherwise the only contract we have is the same one PyTorch `DataLoader` is using with `__del__` and daemon processes: https://github.com/pytorch/pytorch/blob/main/torch/utils/data/dataloader.py#L763

### Additional context

Note that `atexit` won't help if `LightningDataModule` is spawning non-daemon processes I believe.

cc @borda @carmocca @awaelchli @justusschock

**Comment by awaelchli** [comment]
Hey @clumsy 

There are some small inconsistencies in the trainer regarding this yes. This is because the teardown is a very niche hook and not useful for most people, so not much thought has been put there I guess.

Since teardown is meant to be roughly the opposite of setup, and in most occasions it is used assuming no exceptions, I would vote for keeping teardown as is and not call it during exception handling. Also to avoid breaking changes for users who do use it.

So adding `on_exception` sounds reasonable to me.

Is your use case for exception handling strictly tied to DataModule? Because you could otherwise also implement your logic in a Callback (which has the `on_exception` hook), and then you don't need to "wait" for Lightning to add this hook to LDM.

**Comment by clumsy** [comment]
> Since teardown is meant to be roughly the opposite of setup, and in most occasions it is used assuming no exceptions, I would vote for keeping teardown as is and not call it during exception handling. Also to avoid breaking changes for users who do use it.

This makes perfect sense to me, this will also keep it consistent and follow the principle of least astonishment.

> So adding `on_exception` sounds reasonable to me.

Great, in this case I can contribute.

> Is your use case for exception handling strictly tied to DataModule? Because you could otherwise also implement your logic in a Callback (which has the `on_exception` hook), and then you don't need to "wait" for Lightning to add this hook to LDM.

Yes, I thought about using a `Callback`, but leaking the abstractions didn't look particularly attractive - keeping the `teardown` logic encapsulated in the `LightningDataModule` seems more robust. Plus this `Callback` would have to use late binding in my case - the only way I can pass `Trainer` to `LightningDataModule` is via `__init__` (no other `DataHooks` callback provide it) and I need it to access `Trainer` variables, like `global_rank` (e.g. for Tensor Parallel cases). But the `Trainer` callbacks need to be constructed at the same time as the trainer, hence I would end up using something like `trainer.datamodule.teardown()`. This is a workaround available now though, 100%.

**Comment by clumsy** [comment]
@awaelchli I guess the biggest question I have is whether the default implementation in `LightningDataModule` should call `teardown`. It's tempting but probably violates the existing contract.

**Comment by awaelchli** [comment]
I think we wouldn't want that for the reason I explained above. The "Callback" implementation also doesn't do it.
