### ISSUE TITLE
Validation runs during overfit, even when turned off

### ISSUE THREAD

**Issue by tkella47** [Lightning-AI/pytorch-lightning#19618]
### Bug description

I am attempting to overfit a model for demonstration. I am using the CLI and I am using trainer.overfit_batches=.125 and trainer.limit_val_batches=0. 
If trainer.limit_val_batches=0 is run without the overfit_batches, the desired effect of turning off the validation dataloader and epoch is achieved.

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
python cli.py fit -c config.yaml --trainer.limit_val_batches=0 --trainer.overfit_batches=.125
```
```


### Error messages and logs

```
No error message, undesired behavior
```


### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 2.1
#- Lightning App Version (e.g., 0.5.2): N/A
#- PyTorch Version (e.g., 2.0):2.1
#- Python version (e.g., 3.9): 3.10
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: 12.1
#- GPU models and configuration: A100
#- How you installed Lightning(`conda`, `pip`, source): PIP
#- Running environment of LightningApp (e.g. local, cloud): SLURM
```

</details>


### More info

_No response_

cc @borda @justusschock @awaelchli

**Comment by awaelchli** [comment]
Hey @tkella47 

The overfit_batches feature means that the value you set there will replace the other limits like `limit_train_batches` and `limit_val_batches`. So this is intentional behavior. The feature is meant for debugging purposes so you can ensure your model can be overfit, and to assess that you certainly need the validation.

https://github.com/Lightning-AI/pytorch-lightning/blob/096b063d6eeb41567409f4a6b9bac6f5af28ed93/src/lightning/pytorch/trainer/setup.py#L87-L89

The documentation should be made better.

**Comment by awaelchli** [comment]
I'll keep this issue open (thanks for creating it), because we need to make the docs clearer.
