### ISSUE TITLE
Dynamically link arguments in `LightningCLI`?

### ISSUE THREAD

**Issue by EthanMarx** [Lightning-AI/pytorch-lightning#19858]
### Description & Motivation

Is it possible to _dynamically_ link arguments in the `LightningCLI`, say, depending on the module or datamodule subclass that is specified in a config file or at the command line?

cc @borda @carmocca @mauvilsa

**Comment by mauvilsa** [comment]
Maybe more details are needed, since _dynamically_ is a rather general term. Some dynamic linking that already work:
- When the target of a link is a parameter in a subclass, the link is only applied if the selected subclass have such parameter, otherwise the link is ignored. 
- A link can have as source an entire subclass block. And links can have a `compute_fn`, see [link_arguments](https://jsonargparse.readthedocs.io/en/v4.28.0/#jsonargparse.ArgumentLinking.link_arguments). Thus, it is possible to implement a `compute_fn` that depending on the selected subclass returns particular values, which would then be set to the target.

**Comment by EthanMarx** [comment]
Ah. That first point is what I'm looking for! Thanks for the clarification!
