### ISSUE TITLE
is `lightning` and `pytorch_lightning` the same?

### ISSUE THREAD

**Issue by stephanielees** [Lightning-AI/pytorch-lightning#19933]
### Bug description

Hi, I'm probably missing something obvious here, but here's the thing.
I installed `lightning` successfully, but when I want to import it: 
`import lightning as L`

I got the error message:

> ModuleNotFoundError: No module named 'lightning'

However, if I import it like this:
`import pytorch_lightning as L`

it works. And its version is 2.2.5, just like the one in [the official website](https://lightning.ai/docs/pytorch/stable/starter/introduction.html)

Is `pytorch_lightning` library is really the same as library `lightning`? Because all examples on the website show this snippet:
`pip install lightning`
`import lightning as L`

### What version are you seeing the problem on?

v2.2

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- PyTorch Lightning Version (e.g., 1.5.0): 2.2.5
#- Lightning App Version (e.g., 0.5.2): -
#- PyTorch Version (e.g., 2.0): 2.1.2
#- Python version (e.g., 3.9): 3.10.13
#- OS (e.g., Linux): -
#- CUDA/cuDNN version: -
#- GPU models and configuration: GPU T4 x2
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): cloud (Kaggle notebook)
```

</details>

**Comment by Sar2580P** [comment]
Pytorch-Lightning is just a wrapper on Pytorch as mentioned [here](https://pypi.org/project/pytorch-lightning/2.2.5/#:~:text=PyTorch%20Lightning%20is%20the%20lightweight%20PyTorch%20wrapper%20for%20ML%20researchers.%20Scale%20your%20models.%20Write%20less%20boilerplate.)

Lightning is a frame-work which has many other features like : 
 app, pytorch, fabric, data, store
![Screenshot 2024-06-04 220600](https://github.com/Lightning-AI/pytorch-lightning/assets/94839632/148a873b-6ab3-4b66-a3a4-dc31f9a923b5)

Each feature in Lightning is also released as a package... that's why you are seeing Pytorch-Lightning as a package. 
Regarding your issue : 
   I have both installed on my local and I can import both modules .... 
   
Hope I could clear your doubt...
I would appreciate any further discussion.

**Comment by stephanielees** [comment]
Thank you for your help, @Sar2580P. I just want to clarify a couple of things, I hope you don't mind.

So, if I install and import Lightning, I'll get many features in addition to Pytorch-lightning. However, if I only import the Pytorch-lightning, I will still need to import Lightning to be able to use, let's say, Fabric. Is that correct?

Regarding importing pytorch-lightning, I still need to import it as `pytorch_lightning` instead of just `lightning`. But that works for now. Can you please share your code to install and import Pytorch-lightning?

**Comment by Sar2580P** [comment]
[Its absolutely correct. ](https://github.com/Lightning-AI/pytorch-lightning/issues/19933#:~:text=So%2C%20if%20I%20install%20and%20import%20Lightning%2C%20I%27ll%20get%20many%20features%20in%20addition%20to%20Pytorch%2Dlightning.%20However%2C%20if%20I%20only%20import%20the%20Pytorch%2Dlightning%2C%20I%20will%20still%20need%20to%20import%20Lightning%20to%20be%20able%20to%20use%2C%20let%27s%20say%2C%20Fabric.%20Is%20that%20correct%3F)

If you want to use features of pytorch-lightning from lightning then do following:
```
pip install lightning
import lightning.pytorch as L
```

Hope this helps
