### ISSUE TITLE
Teardown trying to copy "meta" tensors

### ISSUE THREAD

**Issue by kvndhrty** [Lightning-AI/pytorch-lightning#20020]
### Bug description

I've got a model template that I'm using with torch.vmap, and to use it I need to store a meta model in my lightning module. However lightning keeps trying to copy the meta model to devices / during teardown etc... This results in an error for the meta tensor, since it does not have a copy method. Any good way to work around this?

This code generates my MLP's template, and during any lightning method that copies things, it dies when ```self.base_model.copy()``` or ```self.base_model.to("device")``` is called.

```python
self.base_model = copy.deepcopy(self.mlp)
self.base_model.to('meta')
```

### What version are you seeing the problem on?

v2.2

### How to reproduce the bug

```python
Run any lightning model with a meta model as a lightning property


self.base_model = copy.deepcopy(self.mlp)
self.base_model.to('meta')
```

### Error messages and logs

```
NotImplementedError: Cannot copy out of meta tensor; no data!
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0): 2.2
#- Lightning App Version (e.g., 0.5.2): 
#- PyTorch Version (e.g., 2.0): 2.2
#- Python version (e.g., 3.9): 3.10
#- OS (e.g., Linux): Windows
#- CUDA/cuDNN version: 12.1
#- GPU models and configuration: 3090
#- How you installed Lightning(`conda`, `pip`, source): conda
#- Running environment of LightningApp (e.g. local, cloud): local
```

</details>

**Comment by awaelchli** [comment]
Hey @kvndhrty 
I think a pretty easy way to work around this is to not register your meta-template model as a submodule. You can easily do that by packing it into a list:
```py
def __init__(self):
    super().__init__()
    with torch.device("meta"):
        self._template_model = [TemplateModel()]
        
    # then access it like so in your other code: 
    self._template_model[0]
    
    # ... or write a getter to return you the template model without indexing
```

I think that the assumption Lightning makes about your model not being on the meta device after training is a reasonable one. Even so before training, since eventually Lightning moves the model to GPU before training. I think it would become quite complex if we had to add logic to ignore such submodules on the meta-device. More so, it would be error-prone, because meta-device initialization is needed for large model training.
So I would like to suggest we don't treat this as a bug.

One other thing you could do is ask yourself whether it is even necessary to have your template model as an attribute at all. Since the creation on meta-device is basically free, you could also just do that on-the-fly whenever you need that. Get the properties you need and store them somewhere. Then you don't need to keep that template model around.

**Comment by kvndhrty** [comment]
@awaelchli I think that is entirely reasonable, I'll pack my module into a list for now. The small re-factor required to init the meta module each time isn't something I'll do this week, but maybe in the near future.

Thank you for the quick response!
