### ISSUE TITLE
pl.TrainResult not found in 2.3.3

### ISSUE THREAD

**Issue by manavkulshrestha** [Lightning-AI/pytorch-lightning#20101]
### Bug description

Documentation I'm looking at says to use `pl.TrainResult`, but I get an attribute error: module 'pytorch_lightning' has no attribute 'TrainResult'. Other issues I see on here seem to specify that I should be using 0.90 or above, which is satisfied since I'm on 2.3.3. Has TrainResult been removed?

### What version are you seeing the problem on?

v2.2, master

### How to reproduce the bug

```python
import pytorch_lightning as pl
print(pl.__version__)
pl.TrainResult
```

### Error messages and logs

```
2.3.3
Traceback (most recent call last):
  File "/local/home/mkulshr/test.py", line 3, in <module>
    pl.TrainResult
AttributeError: module 'pytorch_lightning' has no attribute 'TrainResult'
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- PyTorch Lightning Version (e.g., 1.5.0): 2.3.3
#- PyTorch Version (e.g., 2.0): 2.3.0
#- Python version (e.g., 3.9): 3.11.9
#- OS (e.g., Linux): Linux
#- CUDA/cuDNN version: 12.1
#- GPU models and configuration: 8 Tesla V100-SXM2-16GBs
#- How you installed Lightning(`conda`, `pip`, source): conda
```

</details>

**Comment by awaelchli** [comment]
There aren't any references to `pl.TrainResult` in the docs of recent version of Lightning. If you are reading the docs on our official page, you will see a version number in the top left. This must match the version you have installed. It's been over 2 years since `pl.TrainResult` has been removed. This was before Lightning was even officially stable (1.0). I strongly recommend to upgrade the code.
