### ISSUE TITLE
Documentation for filename convention of save_top_k in ModelCheckpoint

### ISSUE THREAD

**Issue by adosar** [Lightning-AI/pytorch-lightning#20130]
### 📚 Documentation

I am reading the [documentation](https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html#lightning.pytorch.callbacks.ModelCheckpoint) for `save_top_k` of the `ModelCheckpoint` class and I can't understand the filename convention when `save_top_k >= 2`. I will try to explain my confusion with an example.

Suppose that:
```python
checkpoint_callback = ModelCheckpoint(
    filename=foo, 
    save_top_k=3, 
    save_last=True, 
    metric='val_metric', 
    mode='max', 
    ...
)
```

After the training there will be 4 files stored under the `../checkpoints` directory, namely:
```bash
checkpoints
├── last.ckpt
├── foo.ckpt
├── foo-v1.ckpt
└── foo-v2.ckpt
```

Am I right to interpret these as `foo --> top_1`, `foo-v1 --> top_2` and `foo-v2 --> top_3` and `val_metric(foo) > val_metric (foo-v1) > val_metric(foo-v2)?`

If this true, can we append the following to the docs?

> if `save_top_k == k`, the best k models according to the quantity monitored will be saved. If `save_top_k == 0`, no models are saved. If `save_top_k == -1`, all models are saved. Please note that the monitors are checked every `every_n_epochs` epochs. If `save_top_k >= 2` and the callback is called multiple times inside an epoch, and the filename remains unchanged, the name of the saved file will be appended with a version count starting with `v1` to avoid collisions unless `enable_version_counter` is set to `False`. **_If `filename` does not contain formatting options, the filenames for the `top_k` checkpoints will be: `filename` (top-1), `filename-v1` (top-2), ...** 

cc @borda

**Comment by awaelchli** [comment]
That would be a welcome addition. Would you like to do it?

But I'm pretty sure the mapping from the version tag to top-k is not predictable like you wrote. Imagine you have a sequence of test losses, like 0.9, 0.5, 0.2, 0.3. In this case, if we had top_k=2, we would get:

foo.ckpt (0.9)
foo.ckpt (0.9), foo-v1.ckpt (0.5)
foo-v1.ckpt (0.5), foo-v2.ckpt (0.2) (foo.ckpt is deleted)
foo-v2.ckpt (0.2) foo.ckpt (0.3)

As you can see, the end result is foo-v2 is top2, and foo.ckpt is top1.


Remember the versioning is only there to prevent overwriting files.
For practical application, please still consider using a monitor for top-k like it is meant to be used. Otherwise won't be able to identify the top-1 checkpoint unless you load them all to check.

**Comment by awaelchli** [comment]
Yes I guess I mixed up the order of the last two. The main point is that these two are the remaining top checkpoints, and the versioning mechanism exists to prevent overwriting files due to name collisions.

As a sanity check, you can also craft an artificial example returning a sequence of losses using the [handy debugging template](https://github.com/Lightning-AI/pytorch-lightning/blob/master/examples/pytorch/bug_report/bug_report_model.py).

**Comment by awaelchli** [comment]
Yes exactly.
