### ISSUE TITLE
PyTorch Lightning uses deprecated torch_xla function, causing compatibility issues with latest torch_xla versions

### ISSUE THREAD

**Issue by aahila-aws** [Lightning-AI/pytorch-lightning#20419]
### Bug description

PyTorch Lightning uses deprecated torch_xla function, causing compatibility issues with latest torch_xla versions.
In this [file](https://github.com/Lightning-AI/pytorch-lightning/blame/master/src/lightning/fabric/accelerators/xla.py#L112) we see that PyTorch Lightning using an xla function that has been deprecated in the latest versions of [torch_xla](https://pytorch.org/xla/release/r2.5/_modules/torch_xla/runtime.html).

### What version are you seeing the problem on?

master

### Error messages and logs

```
# Error messages and logs here please
```
AttributeError: module 'torch_xla.runtime' has no attribute 'using_pjrt'

### Environment

<details>
  <summary>Current environment</summary>

```
#- PyTorch Lightning Version (e.g., 2.4.0):
#- PyTorch Version (e.g., 2.4):
#- Python version (e.g., 3.12):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
```

</details>

**Comment by byi8220** [comment]
Hi, +1 as this issue is affecting me downstream.

Not sure if this is helpful, but it seems the function in question, [`using_pjrt()`](https://github.com/pytorch/xla/pull/7787/files#diff-b5151ded18fbfdf1debacf597819bd88f7954b7f67f951fa8e131340805e5df5L93-L100) was removed in PR https://github.com/pytorch/xla/pull/7787

My understanding (as an outsider to both this codebase and pytorch itself) is that this function was removed in favor of automatic PJRT device detection (see https://github.com/pytorch/xla/issues/7730).

Could one possible quick fix be to follow the same logic the old `using_pjrt()` function used, and just make a check for `device_type() is not None` as it does?

I could send out a pretty easy one line PR if that's the case

**Comment by lantiga** [comment]
Yes I’m planning to fix this for the upcoming 2.5 release, but if you can send a PR that would be super appreciated!

**Comment by byi8220** [comment]
@lantiga Threw out a proposed fix in https://github.com/Lightning-AI/pytorch-lightning/pull/20442

Added 1 new unit test and the relevant tests pass locally (seems CI needs maintainer approval to run), but I am curious, does your CI pipeline cover this case (i.e. does your CI actually install the `torch-xla` package?)

**Comment by lantiga** [comment]
Thank you @byi8220! We temporarily disabled TPU checks for PyTorch Lightning but we're going to make it come back soon.

**Comment by byi8220** [comment]
Thanks! Just wondering, is there any ETA on the next release?

**Comment by dimzhead** [comment]
def _using_pjrt() -> bool:
    # `using_pjrt` is removed in torch_xla 2.5
    if _XLA_GREATER_EQUAL_2_5:
        from torch_xla import runtime as xr

        return xr.device_type() is not None
    # delete me when torch_xla 2.2 is the min supported version, where XRT support has been dropped.
    if _XLA_GREATER_EQUAL_2_1:
        from torch_xla import runtime as xr

        return xr.using_pjrt()

    from torch_xla.experimental import pjrt

    return pjrt.using_pjrt()


I think these last 2 lines should be removed

> Thanks! Just wondering, is there any ETA on the next release?

**Comment by lantiga** [comment]
Hey, the release will happen in the next 2 weeks

**Comment by BKJackson** [comment]
Can anyone suggest a workaround until the new release is available?
